#!/usr/bin/env bash
# Interactive one-time setup for the geist VPS.
# Walks you through: Docker install, GHCR login, .env creation, DNS/firewall
# reminder, first `docker compose up`, and installing the daily backup cron.
# Safe to re-run: each step detects whether it is already done and asks before changing anything.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

COMPOSE="docker compose -f docker-compose.prod.yml"

# --- helpers ---------------------------------------------------------------
bold() { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '  \033[36m%s\033[0m\n' "$*"; }
warn() { printf '  \033[33m%s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓ %s\033[0m\n' "$*"; }

ask_yn() { # ask_yn "question" [default y/n] -> returns 0 for yes
  local q="$1" def="${2:-y}" ans
  local hint="[Y/n]"; [[ "$def" == "n" ]] && hint="[y/N]"
  read -rp "  $q $hint " ans || true
  ans="${ans:-$def}"
  [[ "$ans" =~ ^[Yy] ]]
}

gen_secret() { openssl rand -hex 32; }

echo
bold "=== geist VPS setup ==="
info "Repo: $REPO_DIR"
echo

# --- 1. Docker -------------------------------------------------------------
bold "[1/6] Docker"
if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
  ok "Docker + compose plugin already installed ($(docker --version))"
else
  warn "Docker (with the compose plugin) was not found."
  if ask_yn "Install Docker now via get.docker.com?"; then
    curl -fsSL https://get.docker.com | sh
    if command -v sudo >/dev/null 2>&1; then
      sudo usermod -aG docker "$USER" || true
      warn "Added $USER to the 'docker' group — log out/in (or run 'newgrp docker') for it to take effect."
    fi
    ok "Docker installed."
  else
    warn "Skipping. Install Docker manually before continuing."
  fi
fi
echo

# --- 2. GHCR login ---------------------------------------------------------
bold "[2/6] GitHub Container Registry login"
info "The images ghcr.io/geist-app/geist-backend|frontend are private, so this host"
info "needs to authenticate to pull them."
if docker system info 2>/dev/null | grep -q 'ghcr.io' || [[ -f "$HOME/.docker/config.json" ]] && grep -q 'ghcr.io' "$HOME/.docker/config.json" 2>/dev/null; then
  ok "A ghcr.io credential already exists in ~/.docker/config.json"
  ask_yn "Log in again anyway?" n && DO_LOGIN=1 || DO_LOGIN=0
else
  DO_LOGIN=1
fi
if [[ "${DO_LOGIN:-0}" == "1" ]]; then
  info "Create a GitHub Personal Access Token with the 'read:packages' scope:"
  info "  https://github.com/settings/tokens  (classic → read:packages)"
  read -rp "  GitHub username: " GH_USER
  read -rsp "  GitHub PAT (read:packages): " GH_PAT; echo
  echo "$GH_PAT" | docker login ghcr.io -u "$GH_USER" --password-stdin
  ok "Logged in to ghcr.io"
fi
echo

# --- 3. .env ---------------------------------------------------------------
bold "[3/6] Environment file (.env)"
if [[ -f .env ]]; then
  ok ".env already exists — leaving it untouched."
else
  info "Creating .env from .env.example with freshly generated secrets."
  PW="$(gen_secret)"
  JWT="$(gen_secret)"
  read -rp "  Postgres user [geist]: " DB_USER; DB_USER="${DB_USER:-geist}"
  read -rp "  Postgres database [geist]: " DB_NAME; DB_NAME="${DB_NAME:-geist}"
  cat > .env <<EOF
# Generated by scripts/setup.sh — configures the running stack on the VPS.
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${PW}
POSTGRES_DB=${DB_NAME}
DATABASE_URL=postgresql://${DB_USER}:${PW}@postgres:5432/${DB_NAME}
JWT_SECRET=${JWT}
IMAGE_TAG=latest
EOF
  chmod 600 .env
  ok ".env created (POSTGRES_PASSWORD and JWT_SECRET auto-generated)."
fi
echo

# --- 4. DNS / firewall reminder -------------------------------------------
bold "[4/6] DNS & firewall"
info "Caddy needs to reach the internet on ports 80 and 443 to obtain TLS certs."
info "Make sure BEFORE the first start:"
info "  • geist-app.com and www.geist-app.com A/AAAA records point at this VPS."
info "  • Ports 80 and 443 are open in the Strato firewall."
ask_yn "Have you done both?" n && ok "Great." || warn "Do this before the app can serve HTTPS."
echo

# --- 5. Start the stack ----------------------------------------------------
bold "[5/6] Start the stack"
if ask_yn "Pull images and start the stack now?"; then
  $COMPOSE pull
  $COMPOSE up -d
  echo
  $COMPOSE ps
  ok "Stack started. Check https://geist-app.com shortly (cert issuance can take ~30s)."
else
  info "Later, run: $COMPOSE up -d"
fi
echo

# --- 6. Backup cron --------------------------------------------------------
bold "[6/6] Automatic backups"
CRON_LINE="0 3 * * * cd ${REPO_DIR} && bash scripts/backup.sh >> ${REPO_DIR}/backups/backup.log 2>&1"
if crontab -l 2>/dev/null | grep -qF "scripts/backup.sh"; then
  ok "Backup cron already installed."
elif ask_yn "Install a daily 03:00 backup cron?"; then
  ( crontab -l 2>/dev/null; echo "$CRON_LINE" ) | crontab -
  ok "Backup cron installed (daily 03:00)."
else
  info "Later, add this cron line:"
  info "  $CRON_LINE"
fi
echo

bold "=== Setup complete ==="
info "Deployments now happen automatically on merge to main (see DEPLOYMENT.md)."
info "Verify the running commit: curl -s https://geist-app.com/api/info"
